import { faPencil, 
  faPaperclip,
  faChartSimple,
  faLock,
  faFile,
  faUser,
  faCalendar,
  faBullhorn, 
  faScroll,
  faCodePullRequest,
  faEye,
  faEyeSlash,
  faArrowRightFromBracket,
  faCaretDown,
  faSortDown,
  faFaceSadTear,
  faBars, } from '@fortawesome/free-solid-svg-icons';

export const icons = {
  records: faScroll,
  paperclip: faPaperclip,
  calendar: faCalendar,
  pencil: faPencil,
  chart: faChartSimple,
  lock: faLock,
  file: faFile,
  user: faUser,
  horn: faBullhorn,
  requests: faCodePullRequest,
  eye: faEye,
  eyeslash: faEyeSlash,
  logout: faArrowRightFromBracket,
  v: faCaretDown,
  down: faSortDown,
  sad: faFaceSadTear,
  burger: faBars,
};
